# Generated by Django 5.2.6 on 2025-09-29 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_authorized_rep_application_child_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='documents_review_notes',
            field=models.TextField(blank=True, help_text='Admin notes on document review'),
        ),
        migrations.AddField(
            model_name='application',
            name='documents_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='documents_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='identity_document',
            field=models.FileField(blank=True, help_text="Upload ID card, passport, or driver's license", null=True, upload_to='applications/identity/'),
        ),
        migrations.AddField(
            model_name='application',
            name='identity_document_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected - Resubmit Required')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='supporting_document_1',
            field=models.FileField(blank=True, help_text='Additional supporting document', null=True, upload_to='applications/supporting/'),
        ),
        migrations.AddField(
            model_name='application',
            name='supporting_document_2',
            field=models.FileField(blank=True, help_text='Additional supporting document', null=True, upload_to='applications/supporting/'),
        ),
        migrations.AddField(
            model_name='application',
            name='supporting_document_3',
            field=models.FileField(blank=True, help_text='Additional supporting document', null=True, upload_to='applications/supporting/'),
        ),
    ]
