# Generated by Django 5.2.6 on 2025-09-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_documents_review_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='documents_review_notes',
            field=models.TextField(blank=True, help_text='Admin notes on document review', null=True),
        ),
    ]
