# Generated by Django 5.2.6 on 2025-10-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_documents_review_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
